name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.14
          enable-cache: true
          cache-dependency-glob: "docker/*/requirements.*.txt"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: x64
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: pip/pre-commit cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pip-cache.outputs.dir }}
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pip-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-pre-commit
      - name: pre-commit #  don't use in self-hosted `- uses: pre-commit/action@v2.0.3`
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          pre-commit install --install-hooks
          pre-commit run -a
